# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d5434492b026b6a8c00f200ef5331bc47b5b522ca2b600011b9336ce6a5a6ca478c6b1fd51a06125d8b08cb2369df298ce7ac471592d5943b4d9ebda7bc27d2

test:
  secret_key_base: 18a7da868ac7006c960b6eed9780c5fa6cdd40d8b3c7ed292ddc62a0aa63df3f8c02e9acc368f5e649ccde3c25007753adaaa6543d452a26634110025fa0dfa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
